exclude: ^static/ | */migrations/.*\.py$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.9
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs
