# Generated by Django 5.2.5 on 2025-08-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_custom_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Optional organization name associated with the account.', max_length=255, verbose_name='company name'),
        ),
    ]
