# Generated by Django 5.2.5 on 2025-08-19 06:44

import django.db.models.deletion
import src.assets.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runs', '0001_setup_orchestration_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to=src.assets.models.asset_upload_path)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='runs.run')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='runs.step')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
